var dataArr = [
	'amazon-animated.gif',
	'anvil.gif',
	'blind-love.gif',
	'blind-love-animated.gif',
	'butterfly-animated.gif',
	'cat.gif',
	'doggy-style.gif',
	'downward-dog.gif',
	'drivers-seat.gif',
	'eiffel-tower-animated.gif',
	'elephant.gif',
	'elevated-jackhammer-animated.gif',
	'face-off-sex-position.jpg',
	'flatiron-animated.gif',
	'flying-missionary.gif',
	'frog-animated.gif',
	'front-and-rear-animated.gif',
	'full-nelson-animated.gif',
	'jackhammer-animated.gif',
	'lap-dance-sex-position.jpg',
	'lazy-dog-animated-1.gif',
	'lotus-animated.gif',
	'love-bug.gif',
	'missionary.gif',
	'musical-chair-animated.gif',
	'on-the-edge.gif',
	'play-ball.gif',
	'reverse-69-animated.gif',
	// 'Spanking-sex-posiotn.jpg',
	'speed-bump-animated.gif',
	'spider-animated.gif',
	'spiderman-animated.gif',
	'spiderman-animated.gif',
	'spooning-animated.gif',
	'squat-animated.gif',
	'stand-and-carry.gif',
	'starfish-animated.gif',
	'superman-animated.gif',
	'table-top-animated.gif',
	'the_hummingbird_sexual_positions__oral_sex_position.jpg',
	'the-chin-rest-animated.gif',
	'the-deep-animated.gif',
	'the-headlock-animated.gif',
	'the-rocker.gif',
	'the-tipster-animated.gif',
	'turtle.gif',
	'two-timing-animated.gif',
	'wall.gif',
	"reverse-cowgirl.gif", "69-animated.gif", "89d91e3d2a134033cba827e0979288d2.gif", "anal-plug.jpg", "missionary-explicit.gif", "pile-driver-NSWF.gif", "missionary-split-NSWF.gif", "avalanche-animated.gif", "back-bend-animated.gif", "body-booster-animated.gif", "boys-on-the-side-animated.gif", "butter-churner-animated.gif", "butterfly-animated.gif", "cats-meow-for-cowgirl.gif", "chair-lift-animated.gif", "chair-tryst-animated.gif", "cowboy-animated.gif", "crouching-tiger-animated-1.gif", "deep-impact-animated.gif", "delicious-for-doggy.gif", "double-dare-animated.gif", "banan-split.gif", "wheel-barrow.gif", "full-nelson.gif", "easy-rider-animated.gif", "elephant-animated.gif", "prone-bone-1.gif", "prone-bone-2.gif", "face-to-face-animated.gif", "filenames.txt", "flatiron-animated.gif", "footsie-animated.gif", "frog-animated.gif", "from-ball-to-wall-animated.gif", "handy-69-animated.gif", "head-rush-animated.gif", "heaven-knows-animated.gif", "highway-to-heaven-animated.gif", "hot-and-spicy-animated.gif", "hula-girl-animated.gif", "jackhammer-animated.gif", "KAMA-31.gif", "kissing-the-pink-animated.gif", "ladies-choice-animated.gif", "launch-pad-animated.gif", "lazy-69-animated.gif", "leaning-tower-animated.gif", "legs-up-animated.gif", "lock-and-load-animated.gif", "magical-for-missionary.gif", "necking-animated.gif", "outstanding-for-oral.gif", "over-the-edge-animated.gif", "piledriver-animated (1).gif", "piledriver-animated.gif", "pretzel-animated.gif", "prone-bone-animated.gif", "raunchy-wrestler-animated.gif", "roller-coaster-animated.gif", "row-row-row-animated.gif", "scissor-animated.gif", "seesaw-animated.gif", "side-saddle-animated.gif", "sideways-animated.gif", "sidewinder-animated.gif", "sitting-bull-animated.gif", "snorkle-1488912374.gif", "spiderman-animated.gif", "spread-eagle-animated.gif", "stand-and-deliver-animated.gif", "sun-salutation-animated.gif", "sweet-seat-animated.gif", "sword-swallower-animated.gif", "tetherball-animated.gif", "the-bodyguard-animated.gif", "the-chin-rest-animated.gif", "the-corkscrew-animated.gif", "the-crazy-cat-animated.gif", "the-firm-animated.gif", "the-flat-back-animated.gif", "the-hammock-animated.gif", "the-headlock-animated.gif", "the-love-seat-animated-1.gif", "the-pin-up-animated.gif", "the-rocker-animated.gif", "the-snow-angel-animated.gif", "the-spork-animated.gif", "the-straddle-animated.gif", "the-swing-animated.gif", "the-throne-animated-1.gif", "the-tipster-animated.gif", "the-tumbler-animated.gif", "trampoline-animated-1.gif", "two-4-one-animated.gif", "UNRNEvl5_o.gif", "up-against-the-wall-animated.gif", "upside-down-animated.gif", "vaginal_vertushka.png", "wall-animated.gif", "wheelbarrow-animated.gif", "whos-your-daddy-animated.gif", "worlds-strongest-animated.gif",  "bent-riding.gif"

];



// https://cumception.com/photos/animated-gifs-of-sex-positions/
// https://sex-positions.online/en-GB/positions/aktivna-zhenschina/
// https://www.sexualpositionsfree.com/animated.html -- https://www.sexualpositionsfree.com/captain-sex-position.html
