var dataArr = [
    'amazon-animated-ezgif.com-crop.gif',
    'anvil.gif',
    'blind-love.gif',
    'blind-love-animated-ezgif.com-crop.gif',
    'butterfly-animated-ezgif.com-crop.gif',
    'cat.gif',
    'doggy-style.gif',
    'downward-dog.gif',
    'drivers-seat.gif',
    'eiffel-tower-animated-ezgif.com-crop.gif',
    'elephant.gif',
    'elevated-jackhammer-animated-ezgif.com-crop.gif',
    'evolved-dog-animated-ezgif.com-crop.gif',
    'face-off-sex-position.jpg',
    'flatiron-animated-ezgif.com-crop.gif',
    'flying-missionary.gif',
    'frog-animated-ezgif.com-crop.gif',
    'front-and-rear-animated-ezgif.com-crop.gif',
    'full-nelson-animated-ezgif.com-crop.gif',
    'jackhammer-animated-ezgif.com-crop.gif',
    'lap-dance-sex-position.jpg',
    'lazy-dog-animated-1-ezgif.com-crop.gif',
    'lotus-animated-ezgif.com-crop.gif',
    'love-bug.gif',
    'missionary.gif',
    'musical-chair-animated-ezgif.com-crop.gif',
    'on-the-edge.gif',
    'play-ball.gif',
    'reverse-69-animated-ezgif.com-crop.gif',
    // 'Spanking-sex-posiotn.jpg',
    'speed-bump-animated-ezgif.com-crop.gif',
    'spider-animated-1-ezgif.com-crop.gif',
    'spiderman-animated-ezgif.com-crop.gif',
    'spiderman-animated-ezgif.com-crop.gif',
    'spooning-animated-ezgif.com-crop.gif',
    'squat-animated-ezgif.com-crop.gif',
    'stand-and-carry.gif',
    'starfish-animated-ezgif.com-crop.gif',
    'superman-animated-ezgif.com-crop.gif',
    'table-top-animated-1-ezgif.com-crop.gif',
    'the_hummingbird_sexual_positions__oral_sex_position.jpg',
    'the-chin-rest-animated-ezgif.com-crop.gif',
    'the-deep-animated-ezgif.com-crop.gif',
    'the-headlock-animated.gif',
    'the-rocker.gif',
    'the-tipster-animated-ezgif.com-crop.gif',
    'turtle.gif',
    'two-timing-animated-ezgif.com-crop.gif',
    'wall.gif',
];



// https://cumception.com/photos/animated-gifs-of-sex-positions/
// https://sex-positions.online/en-GB/positions/aktivna-zhenschina/
// https://www.sexualpositionsfree.com/animated.html -- https://www.sexualpositionsfree.com/captain-sex-position.html
